name: ibh
description: "Indian Business Hub"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

 
  cupertino_icons: ^1.0.8
  sizer: ^3.0.2
  get: ^4.6.6
  http: ^1.1.0
  shared_preferences: ^2.2.1
  flutter_svg: ^2.0.7
  image_picker: ^1.0.4
  google_nav_bar: ^5.0.7
  connectivity_plus: ^6.1.4
  animate_do: ^4.2.0
  cached_network_image: ^3.2.3
  loading_animation_widget: ^1.2.0+4
  intl: ^0.18.0
  pinput: ^2.2.31
  marquee: ^2.2.3
  flutter_staggered_grid_view: ^0.7.0
  readmore: ^2.2.0
  flutter_rating_bar: ^4.0.1
  url_launcher: ^6.2.5
  path_provider: ^2.0.15
  share_plus: ^7.1.0
  palette_generator: ^0.3.3+3
  photo_view: ^0.14.0
  image_cropper: ^5.0.0
  pull_to_refresh_flutter3: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/pngs/
    - assets/svgs/
    - assets/gif/

  fonts:
    - family: fontRegular
      fonts:
        - asset: assets/fonts/NunitoSansRegular.ttf
    - family: fontMedium
      fonts:
        - asset: assets/fonts/NunitoSansBlack.ttf
    - family: fontBold
      fonts:
        - asset: assets/fonts/NunitoSansBold.ttf
    - family: fontExtraBold
      fonts:
        - asset: assets/fonts/NunitoSansExtraBold.ttf
    - family: fontSemiBold
      fonts:
        - asset: assets/fonts/NunitoSansSemiBold.ttf
    - family: fontExtraLight
      fonts:
        - asset: assets/fonts/NunitoSansExtraLight.ttf
    - family: fontLight
      fonts:
        - asset: assets/fonts/NunitoSansLight.ttf
    - family: DM_Sans_Black
      fonts:
        - asset: assets/fonts/DM_Sans/DMSans-Black.ttf
    - family: DM_Sans_Bold
      fonts:
        - asset: assets/fonts/DM_Sans/DMSans-Bold.ttf
    - family: DM_Sans_ExtraBold
      fonts:
        - asset: assets/fonts/DM_Sans/DMSans-ExtraBold.ttf
    - family: DM_Sans_ExtraLight
      fonts:
        - asset: assets/fonts/DM_Sans/DMSans-ExtraLight.ttf
    - family: DM_Sans_Light
      fonts:
        - asset: assets/fonts/DM_Sans/DMSans-Light.ttf
    - family: DM_Sans_Regular
      fonts:
        - asset: assets/fonts/DM_Sans/DMSans-Regular.ttf
    - family: DM_Sans_SemiBold
      fonts:
        - asset: assets/fonts/DM_Sans/DMSans-SemiBold.ttf
    - family: DM_Sans_Medium
      fonts:
        - asset: assets/fonts/DM_Sans/DMSans-Medium.ttf
    - family: Poppins-Black
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Black.ttf
    - family: Poppins-Bold
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
    - family: Poppins-ExtraBold
      fonts:
        - asset: assets/fonts/Poppins/Poppins-ExtraBold.ttf
    - family: Poppins-ExtraLight
      fonts:
        - asset: assets/fonts/Poppins/Poppins-ExtraLight.ttf
    - family: Poppins-Light
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
    - family: Poppins-Regular
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
    - family: Poppins-SemiBold
      fonts:
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
    - family: Poppins-Medium
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf    
    - family: Geologica-Regular
      fonts:
        - asset: assets/fonts/Geologica/Geologica-Regular.ttf 
    - family: Geologica-SemiBold
      fonts:
        - asset: assets/fonts/Geologica/Geologica-SemiBold.ttf 
    - family: Geologica-Medium
      fonts:
        - asset: assets/fonts/Geologica/Geologica-Medium.ttf 
    - family: Cooper-Black-Regular
      fonts:
        - asset: assets/fonts/CooperBlack/Cooper-Black-Regular.ttf 